/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czy_mycppdemo3_cpp_CppActivity */

#ifndef _Included_com_czy_mycppdemo3_cpp_CppActivity
#define _Included_com_czy_mycppdemo3_cpp_CppActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czy_mycppdemo3_cpp_CppActivity
 * Method:    helloFromCpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_czy_mycppdemo3_cpp_CppActivity_helloFromCpp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
