/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czy_mycppdemo3_xiezai_XieZaiActivity */

#ifndef _Included_com_czy_mycppdemo3_xiezai_XieZaiActivity
#define _Included_com_czy_mycppdemo3_xiezai_XieZaiActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czy_mycppdemo3_xiezai_XieZaiActivity
 * Method:    shabusi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_czy_mycppdemo3_xiezai_XieZaiActivity_shabusi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
