/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czy_mycppdemo3_guolu_GuoluActivity */

#ifndef _Included_com_czy_mycppdemo3_guolu_GuoluActivity
#define _Included_com_czy_mycppdemo3_guolu_GuoluActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czy_mycppdemo3_guolu_GuoluActivity
 * Method:    getPressValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_czy_mycppdemo3_guolu_GuoluActivity_getPressValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
