/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czy_mycppdemo3_TestActivity */

#ifndef _Included_com_czy_mycppdemo3_TestActivity
#define _Included_com_czy_mycppdemo3_TestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czy_mycppdemo3_TestActivity
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_czy_mycppdemo3_TestActivity_helloFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
