/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czy_mycppdemo3_MulActivity */

#ifndef _Included_com_czy_mycppdemo3_MulActivity
#define _Included_com_czy_mycppdemo3_MulActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czy_mycppdemo3_MulActivity
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_czy_mycppdemo3_MulActivity_mul
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
