/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czy_mycppdemo3_IcbcActivity */

#ifndef _Included_com_czy_mycppdemo3_IcbcActivity
#define _Included_com_czy_mycppdemo3_IcbcActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czy_mycppdemo3_IcbcActivity
 * Method:    checkLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_czy_mycppdemo3_IcbcActivity_checkLogin
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
