/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czy_mycppdemo3_Java2CActivity */

#ifndef _Included_com_czy_mycppdemo3_Java2CActivity
#define _Included_com_czy_mycppdemo3_Java2CActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czy_mycppdemo3_Java2CActivity
 * Method:    getHelloFromC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_czy_mycppdemo3_Java2CActivity_getHelloFromC
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
