/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czy_mycppdemo3_guolu_GuoluActivity2 */

#ifndef _Included_com_czy_mycppdemo3_guolu_GuoluActivity2
#define _Included_com_czy_mycppdemo3_guolu_GuoluActivity2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czy_mycppdemo3_guolu_GuoluActivity2
 * Method:    getPressValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_czy_mycppdemo3_guolu_GuoluActivity2_getPressValue
  (JNIEnv *, jobject);

/*
 * Class:     com_czy_mycppdemo3_guolu_GuoluActivity2
 * Method:    startMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_czy_mycppdemo3_guolu_GuoluActivity2_startMonitor
  (JNIEnv *, jobject);

/*
 * Class:     com_czy_mycppdemo3_guolu_GuoluActivity2
 * Method:    stopMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_czy_mycppdemo3_guolu_GuoluActivity2_stopMonitor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
