/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_czy_mycppdemo3_SortActivity */

#ifndef _Included_com_czy_mycppdemo3_SortActivity
#define _Included_com_czy_mycppdemo3_SortActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_czy_mycppdemo3_SortActivity
 * Method:    addDatas
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_czy_mycppdemo3_SortActivity_addDatas
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
